# Python: python/commands_config.py
def get_command_dict(instance):
    return {
        "着いてきて": instance._spot_detect_and_follow,
        "ついてきて": instance._spot_detect_and_follow,
        "終了": instance._spot_stop_follow,
        "止まって": instance._spot_stop_follow,
        "停止": instance._spot_stop_follow,
        "休んで": instance._spot_sit_down,
        "座って": instance._spot_sit_down,
        "立って": instance._spot_stand_up,
        "立ち上がって": instance._spot_stand_up,
        "立ち上がれ": instance._spot_stand_up,
        "お辞儀": instance._spot_bow_pose,
        "おじぎ": instance._spot_bow_pose,
        "を辞儀": instance._spot_bow_pose,
        "しゃがんで": instance._spot_squat_pose,
        "伏せ": instance._spot_squat_pose,
        "ふせ": instance._spot_squat_pose,
        # "トラック": instance._spot_thinning,
        "進め": instance._spot_go_to_front,
        "進んで": instance._spot_go_to_front,
        "すすんで": instance._spot_go_to_front,
        "下がって": instance._spot_go_to_back,
        "さがって": instance._spot_go_to_back,
        "後ろに": instance._spot_go_to_back,
        "うしろに": instance._spot_go_to_back,
        "前": instance._spot_go_front_little,
        "後ろ": instance._spot_go_back_little,
        "右": instance._spot_go_right_little,
        "左": instance._spot_go_left_little,
        "うしろ": instance._spot_go_back_little,
        "リセット": instance._spot_reset_audio,
        "プログラム終了": instance._exit_program,
        "プログラム修了": instance._exit_program,
    }
    
def get_keyboard_commands_dict(instance):
    return {
        # "t": instance._make_map,
        # "d": instance._map_download,
        # "u": instance._map_upload_and_sort,
        "r": instance._sit_down,
        "t": instance._stand_up,
        "q": instance._exit_program,
        "w": instance._go_front_little,
        "a": instance._go_left_little,
        "d": instance._go_right_little,
        "s": instance._go_back_little,
        "reset": instance._reset_audio,  # 新たに「reset」コマンドを追加
    }